### ISSUE TITLE
adding links that explain how to connect to the realdash-software

### ISSUE THREAD

**Issue by StefanL38** [janimm/RealDash-extras#10]
Hello,

I'm aware that this is not really an issue about the provided C++-code.
I'm posting it as an "issue" due to the lack of a better suited communication-channel.
If there is one please tell me.

The aduino-sketches demonstrate how use an arduino to send can-bus-frames towards a device that runs realdash.
Though I haven't found any links that would describe how to realise this connection.

A real can bus is not the same as a "simple" serial connection.
Do I have to use a serial-to-canbus-adapter to make it work?
Does realdash offer an opportunity to directly link the arduino to a smartphone or a tablet by using an USB-to-serial adapter?

These are the questions a real newcomer has. I looked up the realdash-board website but I did not find informations like this.

My guessing is it will be not as easy as 
"plug in your smartphone via USB-cable to a PC and the folder with the camera-pictures will be opened automatically"

best regards Stefan

**Comment by janimm** [comment]
Post any questions you may have to our discussion forum: forum.realdash.net
